[defaults]
#config/exps/r9/config_coach_exp_r9e5_disp_se3_mask_val_msoft3_lr2e-5_corr3djoint0sep10_smax.yaml
#run-id: 2021_04_02_v5_r9e1_disp_se3_mask_val_msoft3_lr2e-5_corr3djoint100sep100
run-tag: r9e5_disp_se3_mask_val_msoft3_lr2e-5_corr3djoint0sep10_smax
#run-tag: default
run-start: new

model-load-modules: {
   '2021_03_15_v43_r7e3_disp_lr2e-4_smooth2': ['module_flow', 'module_disp'],
  }
model-freeze-modules: [
   'module_flow',
   ]

wandb-log-metrics: True
wandb-log-state: False
wandb-log-model: False

arch-context-out-channels: 32
arch-context-dropout: True
arch-context-densenet: True

arch-flow-out-channels: 2
arch-flow-dropout: True
arch-flow-res: True
arch-flow-encoder-type: pwcnet

arch-disp-encoder: resnet #resnet | unet | none
arch-disp-separate: True
arch-disp-out-channels: 1
arch-disp-dropout: False
arch-disp-res: False
arch-disp-activation-before-refinement: False
arch-disp-activation: identity # sigmoid | relu
arch-disp-rel-inside-model: False

loss-balance-sf-disp: False

loss-lvl-weights: [4., 0., 2., 1., 1., 1.] # [4., 4., 2., 1., 1., 1.]

loss-disp-photo-lambda: 2.0 # 2.0

loss-disp-smooth-lambda: 2. #0.1 / 832 * 2 * 2 = 0.00012 * 4 = 0.00048
# * 2 cause of disp1/disp2 , * 2 cause of grad_x, grad_y
loss-disp-smooth-order: 2
loss-disp-smooth-edgeweight: 150 # 150 -> 15

loss-disp-flow-cons3d-lambda: 0. # 0.4 # 0.2 * 2 = 0.4 (2. * forward - backward)
loss-disp-flow-cons3d-type: smsf # smsf or chamfer

loss-flow-photo-lambda: 0. # 2. # 2.0
loss-photo-type: ssim # census or ssim

loss-flow-smooth-lambda: 0. # 800. # 800 # 800 # 200 * 2 * 2= 800
loss-flow-smooth-order: 2
loss-flow-smooth-edgeweight: 150 # 150 -> 15 | 10 / 2 (because img_gradient have stride=2)

loss-disp-se3-photo-lambda: 2. # 2. # 2.0
loss-disp-se3-photo-fwdbwd: False

loss-disp-se3-cons3d-lambda: 0. # 0.4 # 0.2 * 2 = 0.4 (2. * forward - backward)
loss-disp-se3-cons3d-type: smsf # smsf or chamfer
loss-disp-se3-cons3d-fwdbwd: False

loss-disp-se3-cons-oflow-lambda: 0.
loss-disp-se3-cons-oflow-type: smsf # smsf or chamfer
loss-disp-se3-cons-oflow-fwdbwd: True

loss-disp-se3-proj2oflow-corr3d-joint-lambda: 0
loss-disp-se3-proj2oflow-corr3d-separate-lambda: 10
loss-disp-se3-proj2oflow-corr3d-separate-mask-lambda: 1
loss-disp-se3-proj2oflow-fwdbwd: False
loss-disp-se3-proj2oflow-level0-only: True

loss-mask-cons-oflow-lambda: 0.1
loss-mask-cons-oflow-fwdbwd: False

loss-mask-reg-nonzero-lambda: 0. #0.001

loss-mask-smooth-lambda: 10
loss-mask-smooth-order: 2
loss-mask-smooth-edgeweight: 150

train-dataset-name: kitti-val
train-dataset-max-num-imgs: 40
val-dataset-max-num-imgs: 40
val-dataset-index-shift: 20
train-seed: 34
train-batch-size: 1
train-accumulate-grad-batches: 1
train-num-epochs-max: 301
val-every-n-epoch: 5

test-sflow-via-disp-se3: True

lr:           0.00002
#lr-scheduler-steps: [5, 10, 15, 20, 25]

# monodepth2
arch-module-se3-resnet-encoder: True
arch-module-se3-input: imgpair # imgpair | features | context
arch-module-se3-intermediate-channels: [256, 256, 256]
arch-module-se3-intermediate-kernelsizes: [1, 3, 3]
arch-module-se3-intermediate-strides: [1, 1, 1]

arch-modules-masks-num-outs: 3
arch-mask-out-init-bias: minus_ten_c0_ten # zero minus_ten zero_c0_ten
arch-mask-activation: softmax
# identity, sigmoid, relu, softmax, sigmoid+normalization (default: sigmoid)