[defaults]
#config/exps/se3/config_coach_exp_disp_se3_md2.yaml
run-id: 2021_02_01_v9_default
run-tag: md2
#run-tag: default
run-start: branch

model-load-modules: [modules_features, modules_context, modules_context_upsampling, module_refinement_context, modules_flow, module_refinement_flow, modules_disp, module_refinement_disp]

wandb-log-metrics: True
wandb-log-state: True
#loss-sflow-cons3d-type: chamfer # smsf or chamfer

# this is maybe required to work
loss-disp-photo-lambda: 2.0 # 2.0
loss-disp-smooth-lambda: 0.00048 #0.1 / 832 * 2 * 2 = 0.00012 * 4 = 0.00048
# * 2 cause of disp1/disp2 , * 2 cause of grad_x, grad_y
loss-disp-smooth-order: 2
loss-disp-smooth-edgeweight: 10 # 150 -> 15

loss-flow-photo-lambda: 0. # 2. # 2.0
loss-flow-smooth-lambda: 0. # 800. # 800 # 800 # 200 * 2 * 2= 800
# this zero is required to work
loss-disp-flow-cons3d-lambda: 0. # 0.4 # 0.2 * 2 = 0.4 (2. * forward - backward)


loss-disp-se3-photo-lambda: 2.0 # 2.0
# this zero is required to work
loss-disp-se3-cons3d-lambda: 0. # 0.4 # 0.2 * 2 = 0.4 (2. * forward - backward)
loss-disp-se3-proj2oflow: 0.

arch-disp-separate: False

# monodepth2
arch-module-se3-resnet-encoder: True
arch-module-se3-input: imgpair # imgpair | features | context
arch-module-se3-intermediate-channels: [256, 256, 256]
arch-module-se3-intermediate-kernelsizes: [1, 3, 3]
arch-module-se3-intermediate-strides: [1, 1, 1]

arch-modules-masks-num-outs: 3
train-seed: 34
test-sflow-via-disp-transf: False
