[defaults]
#config/exps/r4_disp_se3/config_coach_exp_r4e7_disp_se3_bs6_sigmoid.yaml
#run-id: 2021_03_01_v24_r3e11_oflow_disp_se3_scratch_multiscale_res_loadof
run-tag: r4e7_disp_se3_bs6_sigmoid
#run-tag: default
run-start: new

model-load-modules: {
   '2021_03_02_v4_r4e5_disp_se3_bs12': ['module_flow' ],
  }
model-freeze-modules: [
   'module_flow',
   ]

wandb-log-metrics: True
wandb-log-state: True
wandb-log-model: False

arch-context-out-channels: 32
arch-context-dropout: True
arch-context-densenet: True

arch-flow-out-channels: 2
arch-flow-dropout: True
arch-flow-res: True
arch-flow-encoder-type: pwcnet

arch-disp-encoder: resnet #resnet | unet | none
arch-disp-separate: True
arch-disp-out-channels: 1
arch-disp-dropout: False
arch-disp-res: False
arch-disp-activation-before-refinement: False
arch-disp-activation: sigmoid # sigmoid | relu
arch-disp-rel-inside-model: False

loss-balance-sf-disp: False

loss-lvl-weights: [4., 0., 2., 1., 1., 1.] # [4., 4., 2., 1., 1., 1.]

loss-disp-photo-lambda: 2.0 # 2.0

loss-disp-smooth-lambda: 2. #0.1 / 832 * 2 * 2 = 0.00012 * 4 = 0.00048
# * 2 cause of disp1/disp2 , * 2 cause of grad_x, grad_y
loss-disp-smooth-order: 2
loss-disp-smooth-edgeweight: 150 # 150 -> 15

loss-disp-flow-cons3d-lambda: 0. # 0.4 # 0.2 * 2 = 0.4 (2. * forward - backward)
loss-disp-flow-cons3d-type: smsf # smsf or chamfer

loss-flow-photo-lambda: 2. # 2. # 2.0
loss-photo-type: ssim # census or ssim

loss-flow-smooth-lambda: 2. # 800. # 800 # 800 # 200 * 2 * 2= 800
loss-flow-smooth-order: 2
loss-flow-smooth-edgeweight: 150 # 150 -> 15 | 10 / 2 (because img_gradient have stride=2)

loss-disp-se3-photo-lambda: 2 # 2. # 2.0
loss-disp-se3-cons3d-lambda: 0. # 0.4 # 0.2 * 2 = 0.4 (2. * forward - backward)
loss-disp-se3-cons3d-type: smsf # smsf or chamfer

loss-disp-se3-proj2oflow: 0.

train-seed: 34
train-batch-size-optim: 6
train-batch-size: 6

test-sflow-via-disp-se3: True

# monodepth2
arch-module-se3-resnet-encoder: True
arch-module-se3-input: imgpair # imgpair | features | context
arch-module-se3-intermediate-channels: [256, 256, 256]
arch-module-se3-intermediate-kernelsizes: [1, 3, 3]
arch-module-se3-intermediate-strides: [1, 1, 1]
arch-modules-masks-num-outs: 0
