#config/exps/oflow/config_coach_exp_oflow.yaml
run-id: 2021_02_17_v22_oflow
run-tag: oflow
#run-tag: default
run-start: continue

wandb-log-metrics: True
wandb-log-state: True

arch-context-out-channels: 32
arch-context-dropout: True
arch-context-densenet: True

arch-flow-out-channels: 2
arch-flow-dropout: True

arch-disp-out-channels: 1
arch-disp-dropout: True
arch-disp-res: True
arch-disp-activation-before-refinement: False
arch-disp-activation: identity # sigmoid | relu
arch-disp-rel-inside-model: False

loss-balance-sf-disp: False

loss-lvl-weights: [4., 0., 0., 0., 0., 0.] # [4., 4., 2., 1., 1., 1.]

loss-disp-photo-lambda: 0.0 # 2.0

loss-disp-smooth-lambda: 0 #0.1 / 832 * 2 * 2 = 0.00012 * 4 = 0.00048
# * 2 cause of disp1/disp2 , * 2 cause of grad_x, grad_y
loss-disp-smooth-order: 2
loss-disp-smooth-edgeweight: 150 # 150 -> 15

loss-disp-flow-cons3d-lambda: 0. # 0.4 # 0.2 * 2 = 0.4 (2. * forward - backward)
loss-disp-flow-cons3d-type: smsf # smsf or chamfer

loss-flow-photo-lambda: 2. # 2. # 2.0
loss-photo-type: ssim # census or ssim

loss-flow-smooth-lambda: 2. # 800. # 800 # 800 # 200 * 2 * 2= 800
loss-flow-smooth-order: 2
loss-flow-smooth-edgeweight: 150 # 150 -> 15 | 10 / 2 (because img_gradient have stride=2)

loss-disp-se3-photo-lambda: 0 # 2. # 2.0
loss-disp-se3-cons3d-lambda: 0. # 0.4 # 0.2 * 2 = 0.4 (2. * forward - backward)
loss-disp-se3-cons3d-type: smsf # smsf or chamfer

loss-disp-se3-proj2oflow: 0.

train-seed: 34


